from __future__ import annotations

import argparse
import json

from trade_simulator.research_manifest import DEFAULT_SHARED_STATE_DB_PATH, generate_research_manifest_run


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate a dry-run research manifest from periods and grids CSV files.")
    parser.add_argument("--periods-csv", required=True, help="Path to the periods CSV file.")
    parser.add_argument("--grids-csv", required=True, help="Path to the grids CSV file.")
    parser.add_argument(
        "--source-family",
        dest="source_families",
        action="append",
        required=True,
        help="Source family to include in the acquisition dry-run. Repeat to include multiple values.",
    )
    parser.add_argument("--run-root-dir", default="var/research_runs", help="Directory where the run output will be created.")
    parser.add_argument(
        "--shared-state-db-path",
        default=str(DEFAULT_SHARED_STATE_DB_PATH),
        help="Path to the shared state SQLite DB used to resolve reusable acquisitions.",
    )
    parser.add_argument("--run-id", help="Optional explicit run ID. Defaults to an autogenerated UTC-based ID.")
    return parser


def format_research_manifest_run(result: dict) -> str:
    return json.dumps(result, ensure_ascii=False, indent=2)


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    run = generate_research_manifest_run(
        args.periods_csv,
        args.grids_csv,
        source_families=args.source_families,
        run_root_dir=args.run_root_dir,
        shared_state_db_path=args.shared_state_db_path,
        run_id=args.run_id,
    )
    print(
        format_research_manifest_run(
            {
                "run_id": run.run_id,
                "run_dir": str(run.run_dir),
                "period_row_count": run.period_row_count,
                "grid_row_count": run.grid_row_count,
                "eligible_grid_row_count": run.eligible_grid_row_count,
                "manifest_case_count": run.manifest_case_count,
                "acquisition_manifest_count": run.acquisition_manifest_count,
                "unresolved_acquisition_count": run.unresolved_acquisition_count,
                "shared_state_db_path": str(run.shared_state_db_path),
                "manifest_path": str(run.manifest_path),
                "results_index_path": str(run.results_index_path),
                "acquisition_manifest_path": str(run.acquisition_manifest_path),
                "case_acquisition_links_path": str(run.case_acquisition_links_path),
                "cache_metadata_path": str(run.cache_metadata_path),
                "unresolved_acquisitions_path": str(run.unresolved_acquisitions_path),
                "metadata_path": str(run.metadata_path),
            }
        )
    )
    return 0
